local M = {}

M.mainMod = "SUPER"
M.LOCAL_WS_COUNT = 9

M.logout_cmd = "command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"


hl.config({ autogenerated = false })

-- Environment
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-- XDG session
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

-- Input
hl.config({
  input = {
    kb_layout    = "us",
    kb_variant   = "",
    kb_model     = "",
    kb_options   = "",
    kb_rules     = "",

    follow_mouse = 2,
    sensitivity  = 0,

    repeat_rate  = 50,
    repeat_delay = 300,

    touchpad     = {
      natural_scroll = false,
    },
  },
})

return M
