-- hyprland.lua

hl.config({ autogenerated = false })

require("modules.basic")
require("modules.monitors")
require("modules.looks")
require("modules.helpers")
require("modules.rules")
require("modules.binds")
require("modules.autostart")
